package com.td;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication(scanBasePackages = "com.td")
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

}
