package com.tdsource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Configuration
@EnableAutoConfiguration
@ComponentScan
public class App {

    private static Logger LOGGER = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        // String tmp = Paths.get(System.getProperty("user.dir"), "tmp").toString();
        // File repoPath = new File(Paths.get(tmp, "zeppelin").toString());
        // String uri = "https://github.com/apache/zeppelin.git";

        // try (GitProcessor zeppelin = new GitProcessor(uri, repoPath)) {
        //     System.out.println(zeppelin.getCommits());
        // } catch (InvalidRemoteException e) {
        //     LOGGER.error("InvalidRemoteException", e);
        // } catch (TransportException e) {
        //     LOGGER.error("TransportException", e);
        // } catch (GitAPIException e) {
        //     LOGGER.error("GitAPIException", e);
        // } catch (JGitInternalException e) { // destination exists
        //     LOGGER.error("JGitInternalException", e);
        //     // open repository
        // } catch (Exception e) {
        //     LOGGER.error("Exception", e);
        // }
        SpringApplication.run(App.class, args);
    }

}
